language: objective-c

xcode_workspace: ObjcAssociatedObjectHelpers.xcworkspace
xcode_scheme: ObjcAssociatedObjectHelpersLib

script: xctool -workspace ObjcAssociatedObjectHelpers.xcworkspace -scheme ObjcAssociatedObjectHelpersLib test
